### ISSUE TITLE
Unexpected empty page created for Markdown files with dedicated commands when content is merged

### ISSUE THREAD

**Issue by dec0mpiler** [doxygen/doxygen#11709]
According to the Doxygen manual, a Markdown file should not create a dedicated page if it starts with a dedicated command (e.g., \defgroup, \dir) in order to avoid empty pages.
Quote from the documentation:

"Doxygen will not create a dedicated page if the Markdown file starts with a dedicated command (a.o. \defgroup, \dir) to avoid creating an empty page when the file only contains directory or group documentation."

However, when I place such a command at the start of a .md file (e.g., \file, \dir, \defgroup), Doxygen still creates a separate page.
This page appears not only in the navigation panel, but also as an actual HTML page in the output — and it is completely empty except for the title.

Additionally, after these commands (\file, \dir, \defgroup) I try to include content that should be merged into an already existing page defined in another file.
But instead of merging, Doxygen creates a new empty page for this .md file.

**Screenshots**
_Not strictly necessary here, but I can attach a screenshot of the navigation panel and the empty page if required._

**To Reproduce**
Minimal example:

test1.md
```
@page pg1 Issue
test1 file text
```
test2.md
```
@file
@page pg1
sample text
```
Doxyfile (relevant parts):
`GENERATE_TREEVIEW      = YES`

Steps:

1. Run Doxygen with this configuration.
2. Open the generated HTML documentation.
3. Observe:
- An extra entry for `test2.md` appears in the navigation panel.
-  `test2` page is generated but is empty except for the header/title.
- The content from `test2.md` is merged correctly into another page (e.g., the main page).

**Expected behavior**
No dedicated empty page should be generated for a .md file that starts with \file, \dir, or \defgroup,
especially if its content is merged into another page. The file should not appear as a separate page in navigation or output.

Version: 1.9.8

Platform: Ubuntu 24.04.1 LTS

Installation: from distribution package

[issue.tar.gz](https://github.com/user-attachments/files/21719259/issue.tar.gz)

**Comment by albert-github** [comment]
Doxygen 1.9.8 is a bit older (August 25,2023) the current doxygen version is 1.14.0
With doxygen 1.9.8 and also with the current doxygen version I see the problems as indicated.
With the currebt master version (1.15.0 (f1ec8b7482167b0d7466de0c932e6f7cbaa196d1)) I don't see the problem anymore.

I think the problem is fixed but not released.

**Comment by dec0mpiler** [comment]
Tested on version 1.14.0: the problem still reproduces.
Tested on the current master (1.15.0 (f1ec8b7482167b0d7466de0c932e6f7cbaa196d1)): the problem does not reproduce.
Thanks for the quick response, works as expected!

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.15.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
