### ISSUE TITLE
The encoding of the layout file is not taken into account (Origin: bugzilla #591431)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3476]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.5.9* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-08-11 10:55:22 +0000, Laurent Dupuy wrote:

    Even though the character encoding is specified in the layout file, the
    strings in the 'title' attributes are not decoded.
    
    For example, here is a layout file that will produce a wrong output:
    <?xml version="1.0" encoding="ISO-8859-1"?>
    <doxygenlayout version="1.0">
      
      <class>
        <memberdecl>
          <publicattributes title="PropriÃ©tÃ©s publiques"/>
          
        </memberdecl>
      </class>
    </doxygenlayout>

**Comment by albert-github** [comment]
Create attachment that shows the problem (with the 1.5.9 and the current 1.9.7 doxygen versions): [example.tar.gz](https://github.com/doxygen/doxygen/files/11800083/example.tar.gz)

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #10159

**Comment by doxygen** [comment]
@albert-github I think it is better to handle the transcoding directly in the XML parser, instead of doing an extra paring step, so I made an alternative implementation that does this.

**Comment by albert-github** [comment]
@doxygen I thought about this as well and at that moment I decided against it as I also wanted to support the so called BOM  for `UCS` / `UTF-8` (probably a rare situation nowadays, but e.g. Notepad++ supports these BOMs). I was also not sure whether or not this might influence the results of the configuration file and the `xmlcode` etc.

An alternative code update has been made in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
@albert-github I've added support for skipping the UTF-8 BOM. Multi-byte (UCS) encoding is still not supported then, but should be easy enough to avoid.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.8.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
