### ISSUE TITLE
Tabu is broken

### ISSUE THREAD

**Issue by sharris40** [doxygen/doxygen#6769]
Recent updates to LaTeX make it so Doxygen can't even generate its own documentation without the user patching tabu. See https://github.com/latex3/latex2e/issues/111 for an explanation. Tabu is no longer maintained and may be forked. There are a couple of open issues related to tabu not working properly, notably https://github.com/doxygen/doxygen/issues/6034 and https://github.com/doxygen/doxygen/issues/6332.

**Comment by albert-github** [comment]
You claim "Recent updates to LaTeX make it so Doxygen can't even generate its own documentation without the user patching tabu.",  are you referring to the doxygen manual or something else? With the doxygen manual I have no problems at all.

Please give some more details.

**Comment by sharris40** [comment]
I am referring to the Doxygen manual, yes. The problem only happens if you update LaTeX with tlmgr or whatever package manager your TeX Live distribution uses; specifically, the tools package (which may be renamed to latex-tools soon). If you're using the TeX Live bundled with your operating system, it may not have tlmgr, so this problem will only come up when your OS updates that package.

This won't be a major issue for a few months, since not many people will be updating TeX Live packages separately. However, the changes will likely show up in the annual updates in April.

**Comment by albert-github** [comment]
This is not nice. Problem will to get it running with the newer versions but also with older versions of LaTeX. I did a small test with the distributions I have but this gave an error. I posted a comment with the answers from Ulrike Fischer and Frank Mittelbach about how to run with older versions (actually I hope that the tabu package will be fixed).

**Comment by albert-github** [comment]
Some action is on its way ...
https://tex.stackexchange.com/questions/470107/incompatibility-of-fix-in-latex3-latex2e-in-respect-to-unmaintained-tabu-packa

https://github.com/tabu-fixed/tabu

**Comment by sharris40** [comment]
The recent updates to tabu don't entirely fix the problem. I can now make it compile without errors by patching out the `\color@endgroup` lines in `tabu.sty`, but that seems to disable colored tables entirely. Using the old version of tabu with the `\color@begingroup` patch, I can get the PDF looking correct, but `pdflatex` complains and throws out several errors, which causes `make` to bail out.

**Comment by albert-github** [comment]
Did you have a look at https://github.com/tabu-fixed/tabu this is already at CTAN and should enter the TexLive / MikTeX version in the next few days.

**Comment by sharris40** [comment]
I pulled the most recent version from CTAN, as far as I can tell.

**Comment by albert-github** [comment]
Did you use the version from:
https://ctan.org/pkg/tabu
or
https://ctan.org/tex-archive/macros/latex/contrib/tabu

**Comment by sharris40** [comment]
I downloaded them, and they seem to be the same files, and the same as what's on the GitHub repository.

**Comment by albert-github** [comment]
There will probably be a new version of the tabu package (see https://tex.stackexchange.com/questions/471000/tabu-error-since-update), please test this as well and if thee are still errors please report them in the tabu github issue tracker and / or on stackexchange https://tex.stackexchange.com/questions/ask

**Comment by simevo** [comment]
this is hitting debian buster right now: https://bugs.debian.org/920621

can you suggest a patch to doxygen 1.8.15 so that we can have in buster ?

Thanks

**Comment by albert-github** [comment]
Unfortunately no solution yet. For the 1.8.15 it is advised to to use a TeX version from before the change of https://github.com/latex3/latex2e (around the middle of December 2018).

**Comment by simevo** [comment]
I am trying to patch doxygen so that it builds with recent latex, I've had partial success working around the issue with longtabu flexible width columns, but I'm stuck with `DoxyItemize` inside `longtabu`, see:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=920621#42
Any help from latex experts is appreciated  !

**Comment by simevo** [comment]
I made some progress, with this patch:
https://salsa.debian.org/paolog-guest/doxygen/blob/master/debian/patches/longtabu.diff

doxygen itself builds and a few hundreds packages that rely on it also successfully generate the refman.pdf

the price to pay: it's ugly ... example from https://tracker.debian.org/pkg/hwloc, before:
![immagine](https://user-images.githubusercontent.com/8254819/52229502-5adaef80-28b5-11e9-8764-fccfb5dff941.png)

after:
![immagine](https://user-images.githubusercontent.com/8254819/52229627-a9888980-28b5-11e9-846c-c86899b15544.png)

**Comment by albert-github** [comment]
I don't know whether the `X` with positive sizes is possible in the newest version of LaTeX (as I don't have the newest version installed), but when possible and you replace:
`{\begin{longtabu*}spread 0pt [l]{|X[-1,l]|X[-1,l]|X[-1,l]|}}% in/out + name + desc`
by e.g.
`{\begin{longtabu*}spread 0pt [l]{|X[1,l]|X[2,l]|X[6,l]|}}% in/out + name + desc`
the result is not as nice as it was but "bearable".

A minor remark, in the patch you used `c` on a number of places where beforehand there was a `l` or `r`.

**Comment by vng** [comment]
Any progress on it? It's really annoying and I can't find any stable workaround ..

**Comment by albert-github** [comment]
@vng just try to push at the tabu "workaround"  repository.

**Comment by davidcarlisle** [comment]
Note the original author of tabu declared it unmaintained many years ago and it has been running on auto-pilot since then, it is a large barely documented code that patches any number of latex packages and core format  code, it was only a matter of time before it broke.

I set up the tabu-fixed repository (and made a couple of quick fix releases) to give a location where people could report issues and/or fixes, as email to the original author address produced no response after several months.  But I don't have the time to promise that there will be any fixes for more reported issues. The hope is that a knowledgable and motivated user will supply pull requests for tabu-fixed (or better still  offer to pick up the ownership of that repo). 

Sorry but that's just the way it is, we can not promise to pick up every contributed tex package that is abandoned by its author.

**Comment by veelo** [comment]
As mentioned in #6837, the only sustainable solution at this moment seems to be to remove the dependency on the unmaintained tabu package from Doxygen.

**Comment by doxygen** [comment]
I'm looking into reverting part of [the commit](https://github.com/doxygen/doxygen/commit/647b6ac8669cd8ba1e8c60eeb3c2de961c7d6a1b#diff-c661734672eb40c1890c3e88fdc80ad3) that switched from tabularx to tabu in the past. It does mean that the column widths of the tables used to list parameters will no longer adapt to the content. This was the reason to start using tabu. If anyone know a solution for this without using tabu then let me know.

**Comment by albert-github** [comment]
That would be very unfortunately. 

@davidcarlisle any chance that there will be some fixes to the tabu package / an alternative package with similar functionality? ( I know that the original developer of the tabu package is not reachable / has abandoned the package :cry: ). Is there any chance for some sort of "compatibility" mode from  latex3/latex2e.

**Comment by vng** [comment]
@doxygen Hey folks, please, check the latest tabu state from here https://github.com/tabu-fixed/tabu.
When I replaced tabu.sty file in MikTeX package with the latest one from tabu-fixed, everything works fine for me ..

**Comment by albert-github** [comment]
@vng Are you meaning fix 2.10 or 2.9 as the fix 2.10 has been redrawn again (see also: https://ctan.org/pkg/tabu)

**Comment by vng** [comment]
I mean this https://github.com/tabu-fixed/tabu/blob/master/tabu.sty
Seems like it's not in any tabu released packages.

**Comment by veelo** [comment]
> I'm looking into reverting part of [the commit](https://github.com/doxygen/doxygen/commit/647b6ac8669cd8ba1e8c60eeb3c2de961c7d6a1b#diff-c661734672eb40c1890c3e88fdc80ad3) that switched from tabularx to tabu in the past. It does mean that the column widths of the tables used to list parameters will no longer adapt to the content. This was the reason to start using tabu. If anyone know a solution for this without using tabu then let me know.

Maybe https://ctan.org/pkg/ltablex? Found in a comment to https://github.com/sphinx-doc/sphinx/issues/1681 (who by the way made the in hindsight wise decision not to use tabu at the time). I haven't tested it. If we have an isolated test case that behaves badly without tabu, we may be able to look for a solution using this online LaTeX compiler: https://latexbase.com.

**Comment by doxygen** [comment]
I've been experimenting with various `tabu` alternatives; `tabularx`, `ltablex`, and `tabulary` to be precise. Unfortunately not of them come even close to the performance of `tabu` ☹️. All of them mess up column widths and let text overflow or break wrongly to the extend it is not usable at all.


Take for example this small example and paste it in https://latexbase.com:
```tex
\documentclass[12pt]{article}
\usepackage{color}
\usepackage{tabularx}
\usepackage[latin1]{inputenc}

\title{Tables}
\author{Dimitri van Heesch}
\date{21 July 2019}

\begin{document}
\maketitle

A Table
\par%
\begin{tabularx}{\textwidth}{|X|X|X|}%
\hline%
int & field1                  & Field 1 docs\\ \hline
int & field2WithAVeryLongName & Field 2 docs\\ \hline
int & field3                  & Field 3 with a long documentation string to stretch the column a bit\\ \hline
\end{tabularx}

\end{document}
```

You'll get this ugly result:
![image](https://user-images.githubusercontent.com/1300762/61593229-31045380-abdd-11e9-806a-eed19f3bfa6a.png)

Do the same with `\begin{tabu}{|X[-1,l]|X[-1,l]|X[-1,l]|}` and the result is exactly what you would expect.
﻿
![image](https://user-images.githubusercontent.com/1300762/61593333-9278f200-abde-11e9-872c-aef721b29932.png)

Removing tabu from doxygen and shipping some broken alternative is a no go for me; it will lead to too many bug reports and ugly output.

So I still see the following options:
1. Do nothing; keep using tabu hoping it will be fixed and included in LaTeX distributions.
2. Ship the 'fixed' tabu package as part of doxygen hoping it will continue to work good enough for what doxygen needs. This way we do not depend on LaTeX distributions to include tabu.
3. Hope for someone to show how to make one of the other packages behave in a way that tabu does.
4. Drop support for LaTeX altogether (pretty extreme, but hey if it doesn't work anymore...)

**Comment by albert-github** [comment]
I also think that shipping doxygen with another table type then tabu is at the moment not a good alternative (big understatement). The problem that tabu is not working anymore is caused by the facts:
- tabu has no maintainer, but was until the mid of December 2018 still working properly
- in December 2018 the working of the tabu package was broken due to the fact that The LaTeX3 Project Team made a, necessary, fix to https://github.com/latex3/latex2e 

The LaTeX3 Project Team made an attempt to to fix the tabu package https://github.com/tabu-fixed/tabu but didn't succeed and abandoned the package again and changed its name into https://github.com/tabu-issues-for-future-maintainer/tabu 

It would be nice when The LaTeX3 Project Team or other LaTeX specialists could give some advise on a good replacement (and implementation) for the tabu package (@davidcarlisle, @FrankMittelbach, @josephwright).

The options regarding fixing tabu (point 1. and 2.) will probably be a longs shot.

The dropping of the support for LaTeX will be a horrible alternative and in that case users have to create their documents based on another output format and print this to pdf (with probably different, less good, layout and information as in the native LaTeX output) .
For the time being it is still possible to use the 2018 version of the LaTeX distributions, but it will be more and more difficult to obtain that package and one will miss out on bug fixes and new features.

**Comment by davidcarlisle** [comment]
If you want to revert you wouldn't need to revert the entire tex
distribution just the array package (the current distribution includes a
frozen copy of the old array package array-2016-10-06.sty), however it
shouldn't be too hard for someone motivated to update tabu, if you have a
range of test cases, we simply don't have the time to pick up this package
ourselves.

**Comment by albert-github** [comment]
@davidcarlisle thank you for your answer. I see in the CTAN array package the mentioned file, can you enlighten me on how to use this `.sty` file?

I hope someone will be motivated and have the knowledge of (La)TeX to fix the tabu package soon (I would be motivated, but I'm lacking the relevant (La)Tex knowledge).

**Comment by davidcarlisle** [comment]
something like

```
\documentclass{article}

\usepackage{array}[=2016-10-06]
\usepackage{tabu}
\begin{document}

\end{document}

```

**Comment by albert-github** [comment]
Thanks a lot.

I see that we are currently use:
`\RequirePackage{array}`
so this could, probably, be
`\RequirePackage{array}[=2016-10-06]`

One small question remains, this 2016-10-06 is not available in older distributions so here the "plain" array package must be loaded, how would this be done?

**Comment by FrankMittelbach** [comment]
but wouldn't you also need a tabu package from that time given that the current tabu is that "tabu-we-tried-to-fix-it" version? If that is a problem it should not be too difficult to provide an unpatched tabu (or one that rolls back to to that date)

**Comment by albert-github** [comment]
@FrankMittelbach you mean that the current tabu package has some fixes that won't work with together with the `array-2016-10-06.sty` and that actually there should on CTAN also be a in the tabu package a version, in a similar way as for array, be available that that works with the `array-2016-10-06.sty`

**Comment by davidcarlisle** [comment]
something like this, although as Frank says its untested whether that combination works another possibility would be for doxygen itself to distribute the 2018 versions of array and tabu renamed and arrange that the renamed versions are used.

```
\documentclass{article}

\ifx\requestedLaTeXdate\undefined\else
\usepackage{array}[=2016-10-06]
\fi

\usepackage{tabu}
\begin{document}

\end{document}

This loads the old array in new latex formats, in old formats it just loads tabu (which will load array itself)


```

**Comment by FrankMittelbach** [comment]
@albert-github roughly, all I meant is that the tabu on ctan contains our attempt to make tabu work again so it contains fixes because of the corrections in LaTeX and array. So I just don't know how this plays with an old array (it might). My suggestion would be to copy tabu.sty from the last distribution to tabu-doxygen.sty add in
```
\ifx\requestedLaTeXdate\undefined
\usepackage{array}
\else
\usepackage{array}[=2016-10-06]
\fi
```
(and also change the \ProvidesPackage line to use the different name)

and use that ... and then lobby for somebody to pick up tabu and make it work again properly (even the version that you used in the past has several problems).

**Comment by albert-github** [comment]
@davidcarlisle and @FrankMittelbach thanks for the suggestions.

**Comment by FrankMittelbach** [comment]
@albert-github I guess it is clear but if you ship that file tabu-doygen.sty you would then load that instead of tabu as 
```
\usepackage{tabu-doygen}
```
in your documentation. This way everything should work as before and once there is a new maintainer and there is in fact a working tabu for LaTeX then it would easy at a later stage to just get back to loading that new version of tabu instead.

**Comment by albert-github** [comment]
@FrankMittelbach, @davidcarlisle 

I updated my (MikTex) installation and at that moment the doxygen documentation, as expected, didn't build. Ir stops at 100 errors.

I placed as the first packages I loaded:
`\usepackage{array_doxygen}`
which is a copy of the old `array.sty`. This results in the warning:

> LaTeX Warning: You have requested package `array_doxygen',
>                but the package provides `array'.
> 
> Package: array 2018/04/30 v2.4h Tabular extension package (FMi)

but this further looks OK as is loads the old package (similar later on when I load `\usepackage{tabu_doxygen}`.

***Question*** how can I ride of this warning?

Regarding the errors the first error I get is:

> ...
> Package: colortbl 2018/12/12 v1.0d Color table columns (DPC)
> (array.sty
> Package: array 2018/04/30 v2.4h Tabular extension package (FMi)
> \col@sep=\dimen128
> \ar@mcellbox=\box59
> \extrarowheight=\dimen129
> \NC@list=\toks20
> 
> Package array Warning: Column * is already defined on input line 304.
> 
> 
> ! LaTeX Error: Command \extratabsurround already defined.
>                Or name \end... illegal, see p.192 of the manual.

there are here more errors, later on I get a load of:

> ! Missing } inserted.
> <inserted text>
>                 }
> l.74 \end{longtabu}
> 
> I've inserted something that you may have forgotten.
> (See the <inserted text> above.)
> With luck, this will get me unwedged. But if you
> really didn't forget anything, try typing `2' now; then
> my insertion and my current dilemma will both disappear.
> 

and

> I can't figure out why you would want to use a tab mark
> or \cr or \span just now. If something like a right brace
> up above has ended a previous alignment prematurely,
> you're probably due for more error messages, and you
> might try typing `S' now just to see what is salvageable.
> 
> ! Missing \cr inserted.
> <inserted text>
>                 \cr
> l.74 \end{longtabu}

For convenience I attached the complete log file: [refman.zip](https://github.com/doxygen/doxygen/files/3417046/refman.zip)


*** Question*** how to handle this, are there more packages I need to copy in a similar way?

**Comment by FrankMittelbach** [comment]
Am 22.07.19 um 13:39 schrieb albert-github:
> I placed as the first packages I loaded:
> |\usepackage{array_doxygen}|
> which is a copy of the old |array.sty|. This results in the warning:
> 
>     LaTeX Warning: You have requested package |array_doxygen', but the
>     package provides |array'.
> 
>     Package: array 2018/04/30 v2.4h Tabular extension package (FMi)
> 
> but this further looks OK as is loads the old package (similar later on 
> when I load |\usepackage{tabu_doxygen}|.
> 
> /*Question*/ how can I ride of this warning?
> 

when you copy array.sty to a new file name you need to also change the line

\ProvidesPackage{array}[...]

to

\ProvidesPackage{array-doxygen}[...]

so that the file name and what is "provided" match

you should also add a string into the optional argument like

  [... frozen version for doxygen]

where ... is whatever is currently in the argument

Same for any other file that you give a new name.

However, would try to only do that for tabu (-> tabudoxygen) and have 
"array loaded as discussed earlier via

\usepackage{array}[=...]

Otherwise colortbl for example thinks that array is not loaded and thus 
tries to load it on top of array-doxygen which explains the error 
messages you get then.

**Comment by albert-github** [comment]
@FrankMittelbach Thank you for the suggestions, unfortunately I cannot get it to work.

At the beginning of my `tex` file I have:
```
\documentclass{book}
\usepackage{ifthen}
\ifx\requestedLaTeXdate\undefined
\usepackage{array}
\else
\usepackage{array}[=2016-10-06]
\fi
```

but I still see the `colortbl` problems, attached the log file: [refman1.zip](https://github.com/doxygen/doxygen/files/3417458/refman1.zip)

**Comment by FrankMittelbach** [comment]
@albert-github  please provide me with the relevant source files (.tex and your modified .sty and or .cls and I see if I can debug it locally.

**Comment by albert-github** [comment]
@FrankMittelbach very much appreciated.

This are all the, latex related, files required for building the doxygen manual.
I use the make command to generate the manual.

The files: [latex2.zip](https://github.com/doxygen/doxygen/files/3417582/latex2.zip)

**Comment by FrankMittelbach** [comment]
@albert-github ok looks like longtable also had a dependency to that change ...
So:

```
\usepackage{longtable_doxygen}     %  <--- new
\usepackage{tabu_doxygen}
```

[longtable_doxygen.sty.zip](https://github.com/doxygen/doxygen/files/3417908/longtable_doxygen.sty.zip)

hope that'll do the trick. (one could do the same for array, but the code you have on top already does what is needed in terms of rollback)

**Comment by albert-github** [comment]
@FrankMittelbach thanks

I'll give it a try, though I see that between the Miktex version and the version you now provided there is a small difference, in the Miktex version there is around line 430 a `\color@begingroup` and around line 460  a `color@endgroup` and in the `\ProvidesPackage` the text has been appended with "+ FMi change"

**Comment by davidcarlisle** [comment]
Yes exactly: undoing that color group change is the suggested rollback  for tabu (until someone fixes tabu to handle colour safe groups)

**Comment by albert-github** [comment]
@davidcarlisle thanks all clear

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7137

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by Gohico** [comment]
Hi, slightly off topic but I'd be very curious to test the fix from albert-github.
I see that the build is passing in AppVeyor but that no artifacts are stored. Is it possible to download a snapshot build from AppVeyor? I haven't found anything.
Setting up the full build chain on my local machine is a bit of an overkill - especially as I use none of the tools in any other project.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by dm413** [comment]
This fixed the issue for one of my projects, but the other project still fails in MikTex. The MikTex output is:

```
  [27] (group___calling_convention.tex) [28] (group___functions.tex [29]
  [30] [31] [32]
  ! Undefined control sequence.
  \\DoxyParams ...\tabulinesep =1mm\par \ifthenelse
                                                  {\equal {#1}{}}{\begin {lo...
  l.213 \begin{DoxyParams}{Parameters}
```

I'm trying to produce a small example that causes this problem, but no luck so far...

**Comment by FrankMittelbach** [comment]
well `\ifthenelse`is a command defined by ifthen.sty and if that is not known then that package isn't loaded but its commands are used in that project. That shouldn't have anything to do with the problems tabu has/had

**Comment by albert-github** [comment]
@dm413 do you have defined you  own `refman.tex` if so look at the standard `refman.tex` to see the changes regarding the fixes necessary.

**Comment by dm413** [comment]
Yes, sorry. I am using a custom tex header which I did update, but I made an error when updating the second project. When I corrected that error the second project works as well. Thanks for your help.

**Comment by tobihan** [comment]
> This fixed the issue for one of my projects, but the other project still fails in MikTex. The MikTex output is:
> 
> ```
>   [27] (group___calling_convention.tex) [28] (group___functions.tex [29]
>   [30] [31] [32]
>   ! Undefined control sequence.
>   \\DoxyParams ...\tabulinesep =1mm\par \ifthenelse
>                                                   {\equal {#1}{}}{\begin {lo...
>   l.213 \begin{DoxyParams}{Parameters}
> ```
> 
> I'm trying to produce a small example that causes this problem, but no luck so far...

I have the same problem with ppl, see https://bugs.debian.org/943451
The reason seems to be that  \usepackage{ifthen} was removed from doc/doxygen_manual.tex in commit 3f5d4ac5006ac05151a4e06dc00d1c048f3fe6cd . The ppl files don't use the command ifthenelse anywhere, so I think Doxygen should include ifthen itself.

**Comment by albert-github** [comment]
@tobihan 
- which version of doxygen are you using
- which version of MikTeX are you using

Wen this is a persistent problem, please open a new issue and:
- attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
- Please also specify the doxygen version used.

**Comment by tobihan** [comment]
This started happening with doxygen 1.8.16. Using texlive  2019.20200218 from Debian.

**Comment by albert-github** [comment]
This should work, so please create new issue etc. (including the latex output directory) as indicated in my previous comment.

**Comment by mateuszdziuba** [comment]
> This should work, so please create new issue etc. (including the latex output directory) as indicated in my previous comment.

**Comment by mateuszdziuba** [comment]
> > > This should work, so please create new issue etc. (including the latex output directory) as indicated in my previous comment.

asfsf

**Comment by mateuszdziuba** [comment]
> > > > This should work, so please create new issue etc. (including the latex output directory) as indicated in my previous comment.
> 
> asfsf

adf
