### ISSUE TITLE
Links from one Markdown file to another do not work

### ISSUE THREAD

**Issue by wildmichael** [doxygen/doxygen#7595]
I made a small sample that illustrates the problem: https://github.com/wildmichael/doxygen-markdown-linking-problem.

The sample has the following structure
```
.
|-- doc
|   `-- Doxyfile
|-- Makefile
|-- OTHER.md
`-- README.md
```

The `README.md` file references `OTHER.md` simply in the form `[name](OTHER.md)`. The Github Markdown renderer, the one in VS Code etc. all get it right without an issue. However, if doxygen is run from within the `doc` directory, the following warning is produced:
```
/tmp/doxygen/README.md:3: warning: unable to resolve reference to `OTHER.md' for \ref command
```

I would expect doxygen to interpret relative links w.r.t. the file containing them. However, it appears that it uses the current working directory as reference directory. This is entirely inadequate for anything but flat directories.

**Comment by albert-github** [comment]
- Can you please attach your example a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
- Please also specify the doxygen version used.

It might be that the problem is solved in #7032 or is related to it.

**Comment by wildmichael** [comment]
Sorry for the delay...
[doxygen-markdown-linking-problem-master.zip](https://github.com/doxygen/doxygen/files/4658056/doxygen-markdown-linking-problem-master.zip)

**Comment by albert-github** [comment]
Unfortunately still the used doxygen version is missing, though with the 1.8.17 version I do see the problem and the problem is gone with the 1.8.18 version.

I think the problem has been solved in the mean time.

**Comment by wildmichael** [comment]
Sorry, yeah, I had tried with the newest versions. Yes, indeed, this sample works with 1.8.18. But in my real-world code I had an anchor on the heading in `OTHER.md`, i.e. something like:

```
# Another File {#otherfile}
```
And then it still fails. See modified sample in the attachment.
[doxygen-markdown-linking-problem-master.zip](https://github.com/doxygen/doxygen/files/4658583/doxygen-markdown-linking-problem-master.zip)

**Comment by albert-github** [comment]
The second example signals a number of problems:
- the not linking in case of a the relative path
- (on windows) the created, internal, anchor for a file can contain a `:` but this is not possible in an anchor and has to be escaped.

I've just pushed a proposed patch, pull request #7790

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.19.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by jfboismenu** [comment]
I can confirm that this issue is still present in `doxygen` 1.9.1 on macOS (installed via `brew`).
I've adapted the repo steps from this issue to link to link to a file in a subfolder.

I'm getting

`warning: unable to resolve reference to '/Users/boismej/Downloads/linking-to-subfolder/subfolder/OTHER.md' for \ref command`
[linking-to-subfolder.zip](https://github.com/doxygen/doxygen/files/6110356/linking-to-subfolder.zip)

**Comment by PiJ82** [comment]
@jfboismenu, @albert-github I can confirm this bug is still present in doxygen 1.9.4.
Does it make sense to create a new issue for this?

**Comment by albert-github** [comment]
@jfboismenu regarding the problem reported in  https://github.com/doxygen/doxygen/issues/7595#issuecomment-794201969 (a bit late), I think this is a configuration issue as in the `Doxyfile` you have:
```
INPUT                  = ../README.md ../OTHER.md
```
but the file `../OTHER.md` does not exist, I think this line should read:
```
INPUT                  = ../README.md ../subfolder/OTHER.md
```

**Comment by albert-github** [comment]
@PiJ82 
What did you test exactly with the 1.9.4. version, probably best to create a new issue when it is indeed a bug.

**Comment by PiJ82** [comment]
@albert-github Added a small test scenario. Run doxygen from _doxygen_md_bug_, everything is fine. Run doxygen from _.doxygen_md_bug_ (with a leading dot), the error referred to in this issue occurs.
However, it works with doxygen 1.9.2 onward, so I guess I misconfigured something in my initial test setup. The issue seems solved.
[doxygen_md_test.zip](https://github.com/doxygen/doxygen/files/9191169/doxygen_md_test.zip)

**Comment by albert-github** [comment]
@PiJ82 Directories (and file) names starting with a `.` are always problematic (on Linux e.g. they signal hidden files). Good tat the problem is solved for you.

**Comment by PiJ82** [comment]
> Directories (and file) names starting with a . are always problematic (on Linux e.g. they signal hidden files)

That is true. Unfortunately some tools offer default paths containing a dot. For example if working with conan, the default path for the cache is _.conan_ (see https://docs.conan.io/en/1.48/reference/config_files/conan.conf.html).

**Comment by sunzhuoshi** [comment]
> @jfboismenu, @albert-github I can confirm this bug is still present in doxygen 1.9.4. Does it make sense to create a new issue for this? Unfortunately this is a blocker for our project. We updated from doxygen 1.8.14. With 1.8.14, linking between different markdown files worked properly.

You can use following code as a workaround
```
 <a href="doc/changelog.md">changelog</a>
```
to replace
```
[changelog](doc/changelog.md)
```
