### ISSUE TITLE
Markdown relative links - not working for other folders

### ISSUE THREAD

**Issue by bzgec** [doxygen/doxygen#8130]
I don't know if this is a bug or I am doing something wrong but when I try to create a link from `mainpage.md` to `../otherFolder/README.md` the link is broken in html output. I am using Doxygen version 1.8.20.
```
.
├── Doxygen
│   ├── Doxyfile
│   ├── mainpage.md
│   ├── output
│   │   └── html
│   └── versionLog.md
└── otherFolder
    └── README.md
```

In `mainpage.md` I have this code:
```
# Other useful links
- [Version Log](./versionLog.md)
- [Other markdown file from other folder](../otherFolder/README.md)
```
Link to `versionLog.md` is OK, but link to `../otherFolder/README.md` is broken:
![mainpage](https://user-images.githubusercontent.com/34318921/97155902-4835d780-1776-11eb-87ae-98ce969abc4f.png)

I also get warning: `warning: unexpected token TK_EOF as the argument of ref`

Here is project zip: [doxygenMarkdownProblem.zip](https://github.com/doxygen/doxygen/files/5438006/doxygenMarkdownProblem.zip)

**Comment by albert-github** [comment]
First impression was, this has been solved by means of #7032 but this is apparently not the case here. 
Running the example of #7032 with the current version, still, results in correct results.
This must be some corner case, investigating ...

**Comment by albert-github** [comment]
When I start `doxygen` from the `Doxygen` directory I get the error as indicated, when I start from one directory upwards (so directly in `doxygenMarkdownProblem` with `doxygen Doxygen/Doxyfile`) the results are OK.
This is, at the moment, just a workaround, have to see what can be done...

**Comment by bzgec** [comment]
Ok so for now I will just use as you suggested.
Thank you for fast response.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8131

Note: it might be useful to set `STRIP_FROM_PATH` as well.

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by Youda008** [comment]
This is still broken in 1.9.1.

I have
```
├── doc
│   ├── Doxyfile
│   └── main.md
└── README.md
```
I'm trying to reference the README.md from the main.md, but it still can't resolve the \ref

I have a reproduction case in my repo. To reproduce it yourself you have to:
```
git clone https://github.com/Youda008/OpenRGB-cppSDK.git
cd OpenRGB-cppSDK
git checkout 6e71c9181bffd542881929ef0a1570878fab02e5
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make doc
```

**Comment by albert-github** [comment]
The `\ref` command is not intended to link to file names. With local files this is working., for other cases use the markdown syntax like:
`[Test with md type](../README.md)`

**Comment by vvoznesensky** [comment]
> The `\ref` command is not intended to link to file names. With local files this is working., for other casses use the markdown syntax like: `[Test with md type](../README.md)`

It seems that your suggested syntax does not work for comments in source files. Doxygen 1.9.8 prints "warning: unable to resolve reference to 'full-path' for \ref command". I have no idea, why Doxygen writes about \ref command. I use your syntax to reference markdown files by relative paths.

**Comment by albert-github** [comment]
@vvoznesensky 
Doxygen 1.9.8 is a bit older, the current doxygen version is 1.14.0
Can you see what happens with this version and when persistent:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem?
   Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).

**Comment by vvoznesensky** [comment]
> [@vvoznesensky](https://github.com/vvoznesensky) Doxygen 1.9.8 is a bit older, the current doxygen version is 1.14.0 Can you see what happens with this version and when persistent:
> 
>     * Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem?
>       Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).

@albert-github , thank you for your answer. I have found the problem: symbolic links are not accepted in paths. Eliminating symlinks have solved the problem.
