### ISSUE TITLE
Doxygen does not detect inheritance for const methods of templated classes

### ISSUE THREAD

**Issue by jureslak** [doxygen/doxygen#8178]
**Describe the bug**
Consider the following situation where `B<T>` inherits from `A<T>`.
```cpp
/// Class A that takes care of A.
template <typename T>
struct A {
    /// f function.
    virtual void f() const {}
    /// g function.
    virtual void g() {}
};

/// Class B that takes care of B.
template <typename U>
struct B : public A<U> {
    void f() const override {}
    void g() override {}
};
```
The generated documentation for method `B::f` is not inherited from `A::f` and the method list for `B` lists 3 methods:
```
virtual void f () const
void f () const override
void g () override
```
The first two should be collapsed, as latter overrides the former.  See the screenshot of the generated docs:
![image](https://user-images.githubusercontent.com/1394590/99373204-6ac49780-28c1-11eb-8a0d-856b665c4d73.png)

This does not seem to happen with non-const methods. Whether the method is pure virtual or not seems to have no effect. 

However, what matter is the name of the template parameter. If template parameter `U` is renamed to `T`, everything works fine. This is a workaround in some cases, but this seems to appear every time the template parameter is different from the parent class, such as in (full or partial) template specializations, where this cannot be avoided.

**To Reproduce**
Generate the default `Doxyfile` and run `doxygen` over the code in the beginning.  Attached are the source files with some additional examples of template specializations that can be problematic, even if the child class is not.
[a.hpp.txt](https://github.com/doxygen/doxygen/files/5552662/a.hpp.txt)
[Doxyfile.txt](https://github.com/doxygen/doxygen/files/5552632/Doxyfile.txt)

**Version**
Tested with doxygen 1.8.20 (archlinux). The problem appears in versions >= 1.8.17, and is not present in 1.8.16-2, where the docs generate as they should:
![image](https://user-images.githubusercontent.com/1394590/99376368-21764700-28c5-11eb-9826-46fe794c4861.png)

**Additional context**
Additionally, the class inheritance diagram for `A` does not show any descendants, but the inheritance diagram for `B` shows `A` as the parent. It would be nice to show `B` as a child of `A` even when looking at `A` (but this does not happen even in 1.8.16).

**Comment by albert-github** [comment]
With version 1.8.16 I see the behavior as you described, with the current master I also see this behavior. With version 1.8.20 I see a similar behavior as you described only there is one extra line (that I expanded in the following image):
![structB_1_8_20](https://user-images.githubusercontent.com/5223533/99386169-5046ea00-28d2-11eb-9eda-ef5d3b4a466a.png)

I see this all in the file: structB.html

Input  and results of the versions: 1.8.16, 1.8.20 and current master (1.9.0 (af8465e5e2ad2474e520e47ae699389c545236a2)): [results.tar.gz](https://github.com/doxygen/doxygen/files/5553263/results.tar.gz)


Did I miss something? Please check the output as given in the attached file.

I think the problem has been fixed but not released.

**Comment by jureslak** [comment]
No, I don't think you missed anything. I can confirm the 1.8.20 version looks like you described. I think I managed to paste the 1.16 screenshot. 

I also compiled the latest master (fa65bb) and can confirm that it fixes the main issue with the `const` methods.

Ideally, I would also like the diagram in `structA.html`: 
![image](https://user-images.githubusercontent.com/1394590/99511262-56979d80-2988-11eb-8d77-e6e5d34fa1ea.png)

to show that `B` is also a child class, something like:
![image](https://user-images.githubusercontent.com/1394590/99511471-9494c180-2988-11eb-8592-a9a8f1772f33.png)

But this seems to be separate and not that relevant.

**Comment by albert-github** [comment]
@jureslak I think you are right.

We have in this issue the problem of the "extra function" which is correct in the current master, but we still have the problem regarding the "names" of the template parameters, for this I created a new issue #8181

**Comment by jureslak** [comment]
Ok, great. You probably meant "different names of template parameter" in the title of #8181.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
