### ISSUE TITLE
Out-of-line documentation of scoped enums in the same namespace

### ISSUE THREAD

**Issue by pinchartl** [doxygen/doxygen#8281]
When declaring multiple scoped enumerations in a class contained in a namespace, with identically named enumerators, Doxygen complains about not being able to find uniquely matching class members.

```cpp
/**
 * \file main.h
 * \brief Main file
 */

namespace ns {

/**
 * \namespace ns
 * \brief A namespace
 */

class Class
{
public:
	enum class Enum1 {
		Flag,
	};

	enum class Enum2 {
		Flag,
	};
};

/**
 * \class Class
 * \brief A class
 */

/**
 * \enum Class::Enum1
 * \brief A first enum class
 *
 * \var Class::Enum1::Flag
 * \brief A flag of Enum1
 */

/**
 * \enum Class::Enum2
 * \brief A second enum class
 *
 * \var Class::Enum2::Flag
 * \brief A flag of Enum2
 */

} /* namespace */
```

```
/home/laurent/src/test/doxygen/scoped-enums/main.h:34: warning: no uniquely matching class member found for 
  ns::Class::Enum1::Flag

/home/laurent/src/test/doxygen/scoped-enums/main.h:42: warning: no uniquely matching class member found for 
  ns::Class::Enum2::Flag
```

Doxygen version: 1.9.0
Doxyfile: default

The warnings disappear if the namespace is removed.

**Comment by pinchartl** [comment]
Gentle ping on this issue, if someone had a chance to look at it, it would be very appreciated.

**Comment by doxygen** [comment]
@pinchartl Thanks for the reminder. I've just committed a change to address this problem. Please verify if it indeed fixes it for you.

**Comment by pinchartl** [comment]
You're amazing :-) This fixes the issue.

**Comment by albert-github** [comment]
Please don't close the issue, reopening issue, please don't close the issue as this will be done at the moment of an official release.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by randolf** [comment]
This problem persists in v1.9.6 -- I just downloaded this version and tried it, and it doesn't document any **enum**s in a namespace that are not in a class.

**Comment by albert-github** [comment]
@randolf 
Looks like another issue.
Please open a new issue and attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
