### ISSUE TITLE
Regression: In Python/xml output, refid and qualified name of base compound not resolved under certain conditions

### ISSUE THREAD

**Issue by Stewori** [doxygen/doxygen#8560]
**Describe the bug**
Recently I observed (in xml) the following regression in linking the parent of a class.
Assume you have a file ``pack/C.py`` with the content:

```
from pack import B

class D(B):
  pass

```
and the file ``pack/__init__.py`` does not declare ``B`` itself but imports it, let's say from ``pack/A.py``.

``pack/__init__.py``:

```
from A import B
```

``pack/A.py``:

```
class B:
    pass
```

Now let's look at the resulting ``classpack_1_1C_1_1D.xml``. It contains the line
```
<basecompoundref prot="public" virt="non-virtual">B</basecompoundref>
```
Note the missing ``refid`` and lack of a fully qualified name of B. This used to work!
Some Doxygen commits ago it still was

```
<basecompoundref refid="classpack_1_1A_1_1B" prot="public" virt="non-virtual">pack.A.B</basecompoundref>
```

Unfortunately, if we add a file a file ``C2.py`` much like ``pack/C.py`` but located in the parent folder of ``pack``:

```
from pack import B

class D2(B):
  pass
```
Then in ``classC2_1_1D2.xml`` one always has, in current Doxygen and in recent Doxygen, the version with the missing link
```
<basecompoundref prot="public" virt="non-virtual">B</basecompoundref>
```
The fact that it used to work for ``pack/C.py`` shows that Doxygen in principle *can* resolve such a link. It would be great if this worked regardless of where ``C`` or ``C2`` are located (within the project).

**Expected behavior**

I expect the basecompoundref to be properly resolved like it used to be, i.e. get the output
```
<basecompoundref refid="classpack_1_1A_1_1B" prot="public" virt="non-virtual">pack.A.B</basecompoundref>
```

**To Reproduce**
Find the example from above and doxygen config attached. The issue is demonstrated like mentioned above.
Note that the included xml and html folders contains files created *before* the regression, i.e. using a Doxygen clone from 2021-03-17. The current behavior can be reproduced by running current Doxygen on the provided setup.
[regression.zip](https://github.com/doxygen/doxygen/files/6509757/regression.zip)

**Version**
Tested with self-compiled clone from 2021-05-12:
```
/blah/doxygen/build/bin/doxygen -v
1.9.2 (cd998a7164e30cee896cccd190846b79ebb4355f)
```
I did not identify the precise commit that caused the regression. However, the latest release 1.9.1 still works as expected regarding this issue. Also, I know that it still works with a Doxygen clone I made on March 17 (2021-03-17).

`lsb_release -a`:
```
LSB Version:    core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:    LinuxMint
Description:    Linux Mint 18 Sarah
Release:    18
Codename:    sarah
```

**Comment by albert-github** [comment]
@doxygen
According to a bisection:
```
0d05e79d67b5b808918541f429b06805207e8bdb is the first bad commit
commit 0d05e79d67b5b808918541f429b06805207e8bdb
Date:   Thu Mar 11 23:05:13 2021 +0100

    Refactoring: Replaced QDir with Dir

    - Dir is based on ghc::filesystem, a std::filesystem compatible
      implementation that does not require C++17.
```
Looks a contradiction with the "I know that it still works with a Doxygen clone I made on March 17 (2021-03-17)." though this is not the case, the commit was added to the doxygen master on 18 March 2021 21:57

**Comment by albert-github** [comment]
I did some further investigations.

The `__init__.py` file is a bit of an odd one out in the handling and it looks like the old situation it was a bit of luck that it did work.

The problem looks like to have to do with the way the input files are sorted and handled. In the version 1.9.1 situation the order is illustrated best by:
```
Parsing files
Reading .../issue_8560/C2.py...
Parsing file .../issue_8560/C2.py...
Reading .../issue_8560/pack/__init__.py...
Parsing file .../issue_8560/pack/__init__.py...
Reading .../issue_8560/pack/A.py...
Parsing file .../issue_8560/pack/A.py...
Reading .../issue_8560/pack/C.py...
Parsing file .../issue_8560/pack/C.py...
```
for the current master this is:
```
Parsing files
Reading _8560/C2.py...
Parsing file _8560/C2.py...
Reading _8560/pack/A.py...
Parsing file _8560/pack/A.py...
Reading _8560/pack/C.py...
Parsing file _8560/pack/C.py...
Reading _8560/pack/__init__.py...
Parsing file _8560/pack/__init__.py...
```
Note here the moment that `__init__.py` is handled.

When looking at the, HTML, file `namespaces.html` we see for version 1.9.1 (I made the links red for better visibility):
![image](https://user-images.githubusercontent.com/5223533/118960133-437b7f80-b963-11eb-9848-0712d6f2b395.png)

and for the current master:
![image](https://user-images.githubusercontent.com/5223533/118960325-7756a500-b963-11eb-8838-fbedafe11709.png)

(Note the color of `pack`).

It looks like that when a "master" package (here `pack`) would be added later to the namespace list than one of the sub packages (like `pack.C` this doesn't happen (properly).
With version 1.9.1 we can also accomplish this problem by renaming `pack/A.py` into `pack/___A.py` and `pack/C.py` into `pack/___C.py`.

**Comment by doxygen** [comment]
The namespace/package was marked as "artificial" when finding the class first and this status was not reset when the namespace/package was found later.

Please verify if the referenced commit I just pushed fixes the problem.

**Comment by Stewori** [comment]
Unfortunately, it appears the issue was not fixed by that commit. Using a fresh clone from just now, the issue still occurs on the provided setup in ``regression.zip``.
```
/doxygen_2021-05-21/doxygen/build/bin/doxygen --version
1.9.2 (525f577318783e9cba89b473c11b770a03760fbc)
```

Given that you mention "artificial" I observed that in Python, the location/file attribute of namespace compounds reads ``[generated]`` since some weeks (I suppose). Until at least 17th of March it was still ``package_name/__init__.py``:

Used to be:
```
<compounddef id="namespacepack" kind="namespace" language="Python">
    ...
    <location file="pack/__init__.py" line="1" column="1"/>
</compounddef>
```

Now it is:
```
<compounddef id="namespacepack" kind="namespace" language="Python">
    ...
    <location file="[generated]" line="1" column="1"/>
</compounddef>
```
Does it have to do something with this?
(I find this new behavior somewhat annoying actually, but not annoying enough to file a proper issue about it. I can do if you want.)

**Comment by albert-github** [comment]
Looking at the collaboration / inheritance diagram in html/classpack_1_1C_1_1D.html we see also that with the 1.9.1 version there is a relation "pack.C.D" -> "pack.A.B" and in the master version we see "pack.C.D" -> "B"

**Comment by doxygen** [comment]
I've pushed another fix that hopefully addresses the remaining issue. Let me know if I missed anything.

**Comment by albert-github** [comment]
When I compare the xml from the current master (fbeef943bd0713d0dc3e83b9148e9dd0b69ea35b) and the 1.9.1  version I see stil quite a few differences in respect to the problems mentioned.

Also the problem commented by me (in https://github.com/doxygen/doxygen/issues/8560#issuecomment-845933334) is stil present (file: html/classpack_1_1C_1_1D.html):
**1.9.1**
![image](https://user-images.githubusercontent.com/5223533/119233949-9738c500-bb2b-11eb-95c3-f8c27e8c4ae9.png)

**Current master**
![image](https://user-images.githubusercontent.com/5223533/119233929-7ff9d780-bb2b-11eb-8d0c-fd6cf6c88a99.png)

**Comment by doxygen** [comment]
@albert-github This is very strange.

For me to page looks like this:

<img width="770" alt="Screenshot 2021-05-22 at 20 05 52" src="https://user-images.githubusercontent.com/1300762/119236724-4203b000-bb39-11eb-93df-786789fdb73b.png">

Does it help if you remove the output directory and run doxygen again?

**Comment by Stewori** [comment]
I have to confirm @albert-github 's observation. Also in the xml I still get
```
<basecompoundref prot="public" virt="non-virtual">B</basecompoundref>
```
in ``classpack_1_1C_1_1D.xml`` and ``class_C2_1_1D2.xml`` likewise.

``classpack_1_1C_1_1D__inherit__graph.png``:
![classpack_1_1C_1_1D__inherit__graph](https://user-images.githubusercontent.com/4356260/119237852-5b0f5f80-bb3f-11eb-9476-cc0014421a83.png)

For D2 this looks similarly and also the collgraphs look this way.

Built using a fresh clone, cloned half an hour ago. xml and html directories removed before build.
```
/doxygen_test/issue_Python_regression_superclass_link/2 $ '/data/workspace/linux/doccy/doxygen_test/doxygen_2021-0
5-22/doxygen/build/bin/doxygen' --version
1.9.2 (5ee697da531e020e5f0354f22ef2b929cce7c823)
```

@doxygen given the strange difference in our results, maybe you could double check that with the commit everything went right. E.g. no file was forgotten to be staged or so. Or check the diff between a fresh clone and your workspace version. If that shows nothing, can it be caused by a different system? Strange phenomenon indeed.

**Comment by doxygen** [comment]
@Stewori , @albert-github I did rerun the example with a fresh clone+build both on mac and linux, and the result for me are always the same.

I've attached the files and Doxyfile I used and the output I got, just for you to see if you get the same results as me:
[files.zip](https://github.com/doxygen/doxygen/files/6527009/files.zip)

- `version.txt` is the output of `doxygen -v`
- `output_mac.txt` is the output of running the freshly built doxygen executable on my Mac
- `output_linux.txt` is the output of running the freshly built doxygen executable on Linux (running via vmware).

**Comment by Stewori** [comment]
Using everything from your files.zip (removing your xml and html folders), processing with apparently the same Doxygen version (for proof see output.txt: ``Doxygen version used: 1.9.2 (5ee697da531e020e5f0354f22ef2b929cce7c823)``) results in
[files_stewori.zip](https://github.com/doxygen/doxygen/files/6527031/files_stewori.zip)
containing the results I described in my last post.

Then the only explanation is a difference in a linked library...?

I offer to assist in debugging. Is there e.g. some place in the code where a genuine ``printf`` would be enlightening (etc)? Just let me know and I will check it out.

**Comment by Stewori** [comment]
It occurred to me the cmake output might be of interest. Mine is as follows:

```
cmake -G "Unix Makefiles" ..
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Found FLEX: /usr/bin/flex (found version "2.6.0") 
-- Found BISON: /usr/bin/bison (found version "3.0.4") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for iconv_open
-- Looking for iconv_open - found
-- Performing Test ICONV_COMPILES
-- Performing Test ICONV_COMPILES - Success
-- Found Iconv: In glibc  
-- One (and only one) of the ICONV_ACCEPTS_... tests must pass
-- Performing Test ICONV_ACCEPTS_NONCONST_INPUT
-- Performing Test ICONV_ACCEPTS_NONCONST_INPUT - Success
-- Performing Test ICONV_ACCEPTS_CONST_INPUT
-- Performing Test ICONV_ACCEPTS_CONST_INPUT - Failed
-- The javacc executable not found, using existing files
-- Configuring done
-- Generating done
-- Build files have been written to: /doxygen_test/doxygen_2021-05-22/doxygen/build
```

Then another idea. Do you think it would be helpful to check Doxygen's behavior on this issue on the CI?

**Comment by albert-github** [comment]
I reran the the issue again  with doxygen version 5ee697da531e020e5f0354f22ef2b929cce7c823 the files.zip provided by @doxygen, removed the html and xml directory. The results are still not good, my results: [files_windows.tar.gz](https://github.com/doxygen/doxygen/files/6527756/files_windows.tar.gz)

I think a notable difference is (see also my comment https://github.com/doxygen/doxygen/issues/8560#issuecomment-844948627):
```
< Reading /mnt/hgfs/dimitri/doxygen.dev/mail/1.9.1/issue8560/files/pack/A.py...
< Parsing file /mnt/hgfs/dimitri/doxygen.dev/mail/1.9.1/issue8560/files/pack/A.py...
< Reading /mnt/hgfs/dimitri/doxygen.dev/mail/1.9.1/issue8560/files/pack/__init__.py...
< Parsing file /mnt/hgfs/dimitri/doxygen.dev/mail/1.9.1/issue8560/files/pack/__init__.py...
< Reading /mnt/hgfs/dimitri/doxygen.dev/mail/1.9.1/issue8560/files/pack/C.py...
< Parsing file /mnt/hgfs/dimitri/doxygen.dev/mail/1.9.1/issue8560/files/pack/C.py...
< Reading /mnt/hgfs/dimitri/doxygen.dev/mail/1.9.1/issue8560/files/C2.py...
< Parsing file /mnt/hgfs/dimitri/doxygen.dev/mail/1.9.1/issue8560/files/C2.py...
---
> Reading D:/issue_8560/files/C2.py...
> Parsing file D:/issue_8560/files/C2.py...
> Reading D:/issue_8560/files/pack/A.py...
> Parsing file D:/issue_8560/files/pack/A.py...
> Reading D:/issue_8560/files/pack/C.py...
> Parsing file D:/issue_8560/files/pack/C.py...
> Reading D:/issue_8560/files/pack/__init__.py...
> Parsing file D:/issue_8560/files/pack/__init__.py...
```
i.e. the order in which the files are processed.

In my comment:  https://github.com/doxygen/doxygen/issues/8560#issuecomment-844948627 I mentioned already:
> With version 1.9.1 we can also create this problem by renaming `pack/A.py` into `pack/___A.py` and `pack/C.py` into `pack/___C.py` (i.e. with 3 underscores).

and in the original issue it is written:
> Then in `classC2_1_1D2.xml` one always has, in current Doxygen and in recent Doxygen, the version with the missing link

This leads me to the idea that there is a fundamental ordering problem (of the namespaces).

Lets do an experiment on windows and rename:
- `pack/C.py` to `pack/_C.py`
- `C2.py` to `pack/_C2.py`
- rest can remain unchanged

The relevant part from the output log is now:
```
Reading D:/issue_8560/files/pack/A.py...
Parsing file D:/issue_8560/files/pack/A.py...
Reading D:/issue_8560/files/pack/__init__.py...
Parsing file D:/issue_8560/files/pack/__init__.py...
Reading D:/issue_8560/files/pack/___C.py...
Parsing file D:/issue_8560/files/pack/___C.py...
Reading D:/issue_8560/files/_C2.py...
Parsing file D:/issue_8560/files/_C2.py...
```
so this is again the order as found by @doxygen and the complete results look to me OK.

@Stewori can you confirm that these results look OK i.e. complete.

@doxygen you can probably get the wrong results
- running on a, virtual, windows system
- by renaming some files as well (but probably in a bit of a different way (maybe using numbers or lowercase letters)


The new results: [files_windows_reordered.tar.gz](https://github.com/doxygen/doxygen/files/6527764/files_windows_reordered.tar.gz)

**Comment by doxygen** [comment]
@albert-github I think you are indeed right in that the order of processing is causing the difference. That order should have been the same on all platforms since the list of files is sorted (see https://github.com/doxygen/doxygen/blob/5ee697da531e020e5f0354f22ef2b929cce7c823/src/doxygen.cpp#L11177). Sorting is supposed to be case insensitive and work on the full file name, so doxygen should have processed `C2.py` before `pack/*`, which is not the case for my run. I'll look into that.

The other issue is then that the order should of course not impact the processing results. Since namespaces/packages are processed before classes, the classes should not introduce additional artificial namespaces as seems to be the case if `C2.py` is processed first.

**Comment by doxygen** [comment]
Ok, small update: `Doxygen::inputNameLinkedMap` was indeed sorted but then `g_inputFiles` was used to actually iterate over the files 🙄. Sorting that list as well, at least gives me the same (wrong) results.

**Comment by albert-github** [comment]
Aside note:
@doxygen, just came into my mind again that we had a small, private, discussion regarding an issue that popped up at Fossies i.e.
```
ASSERT: "fd!=0" in .../doxygen-git/doxygen/src/doxygen.cpp (9552)
```
this was also not reproducible and I also had the idea that this might come from the order of the processing of the files. We were not able to reproduce the problem (and Fossies uses a Suse system, so again a bit another component).

Looks like this problem might have to do something with the current issue as well as our conversation about it started on March 24, 2021 (and from the files I have I see that the first observed occurrence of the "fd!=0" problem was on March 22, 2021)

Maybe your remark in comment https://github.com/doxygen/doxygen/issues/8560#issuecomment-846534106 might already solve the "Fossies issue" (makes it probably consistent with other systems).

I think that when the problem of this issue has been fixed we should also ask for some reruns on Fossies (will be requested by me at that moment).

**Comment by doxygen** [comment]
Ok, another attempt to fix this problem. 

The directory content is now sorted (similar to when `QDir` was still used) so it should give the same results on all platforms (while still allowing to specify a specific order via `INPUT`, I tested with `INPUT = C2.py pack` and `INPUT = pack C2.py`). 

Imports of package files (`__init__.py`) are now processed first, before processing the other files so that when something is imported from a package it is already resolved and doesn't depend on the processing order.

**Comment by doxygen** [comment]
> 
> I think that when the problem of this issue has been fixed we should also ask for some reruns on Fossies (will be requested by me at that moment).

Yes, I think that is a good idea.

**Comment by albert-github** [comment]
Unfortunately, I think the fundamental problem is still present.

I created an artificial situation to signalize the problem:
```
D:\issue_8560\files\C2.py
D:\issue_8560\files\Doxyfile
D:\issue_8560\files\output_linux.txt
D:\issue_8560\files\output_mac.txt
D:\issue_8560\files\output_windows_reorderd.txt
D:\issue_8560\files\pack
D:\issue_8560\files\version.txt
D:\issue_8560\files\pack\__A.py
D:\issue_8560\files\pack\__c.py
D:\issue_8560\files\pack\__init__.py
```
and now we see again the wrong order:
```
Reading D:/issue_8560/files/C2.py...
Parsing file D:/issue_8560/files/C2.py...
Reading D:/issue_8560/files/pack/__A.py...
Parsing file D:/issue_8560/files/pack/__A.py...
Reading D:/issue_8560/files/pack/__c.py...
Parsing file D:/issue_8560/files/pack/__c.py...
Reading D:/issue_8560/files/pack/__init__.py...
Parsing file D:/issue_8560/files/pack/__init__.py...
```

Example: [files_windows_reordered_2.tar.gz](https://github.com/doxygen/doxygen/files/6528495/files_windows_reordered_2.tar.gz)

**Comment by albert-github** [comment]
Some thoughts.

I think it is a very complex situation we have to handle here as `__init__.py` is a bit an odd one out (also compared with other languages).

Best would be that the namespace defined in the `__init__.py` would land at the right place in the namespace tree and that the namespaces depending on it would automativally pick this up, but I think this is very far fetched,.

So we have (as I can see)  the following situations:
1. `__init__.py` is added explicitly in the `INPUT` tag
2. `__init__.py` is added implicitly when going, recursively, through a directory (tree).
3. a mix of the above 2

In case 1. it is the responsibility of the user that the `__init__.py` added at the right place
In case 2. in this case the files of a directory have to be found and it has to be checked whether or not `__init__.py` is present, in this case this file should be placed at the top of the list.
In case 3. the considerations of both points have to be respected (i.e. no change of order of the explicitly added and seeing to it that `__init__.py` is processed at the right place when added when going through a dircetry.

I first thought about removing all `__init__.py` from the input list and adding them in front of the list, but this could / would violate the order specified in the `INPUT` tag.

Note the usage of Multi-threading input might be complicating the process a bit.

**Comment by doxygen** [comment]
@albert I tried to make sure the code works regardless of the order in which the files are processed 
(one can always get the files processed in any order by listing each file individually using the `INPUT` option, or enabling the multi-threading input processing).

In your modified example you renamed `A.py` to `__A.py`. As a result the `from A import B` in `__init__.py` does no longer work since `A.py` does not exist. If I change the code in `__init__.py` to `from __A import B` it works again. So this is not a bug in doxygen in my opinion.

**Comment by albert-github** [comment]
I thought I checked for the usage of the names but apparently I overlooked this one.
It looks indeed better but in the file `html/____A_8py.html` I see now:
![image](https://user-images.githubusercontent.com/5223533/119321724-40430500-bc7d-11eb-8a63-6c233286b4d5.png)

and with the 1.9.1. version I see:
![image](https://user-images.githubusercontent.com/5223533/119321805-53ee6b80-bc7d-11eb-8c7f-d52e1ef0151f.png)

The difference I see is the fact that now the `pack` and `pack.__A` are mentioned as namespaces and with the 1.9.1 version just the `pack__A`. I'm not 100% sure whether or not this is correct / intended.
Similar of course in `html/____c_8hpy.html`.
In the file `html/____init_____8py.html` the `pack` is added, I think this is correct (and has a positive effect on `annotated.html` as well.

The fact that the word "namespace" is added is an improvement.

Hopefully @Stewori can also shine a light on the XML results.

**Comment by Stewori** [comment]
Thank you for fixing this! I can confirm that with a recent clone also the xml results are how they should be. Great work!

**Comment by Stewori** [comment]
> The difference I see is the fact that now the pack and pack.__A are mentioned as namespaces and with the 1.9.1 version just the pack__A. I'm not 100% sure whether or not this is correct / intended.

At least IMHO it is a good thing that ``pack`` is listed as a separate namespace, because it actually is one. As a matter of fact, for Python both packages (by means of ``__init__.py``) and modules are declared ``kind=namespace`` by Doxygen. However that is how it has always been. (To distinguish them I used to check for ``file=__init__.py`` but that recently changed to ``file=[generated]``.)

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
