### ISSUE TITLE
XML: Issue with ``$`` sign in Java identifiers

### ISSUE THREAD

**Issue by Stewori** [doxygen/doxygen#8617]
**Describe the bug**
Processing Java code
```
public class Test {
    public int someField$;
    public void some$method() {}
}
```
results in the following xml snippet:
```
<memberdef kind="variable" id="classTest_1a815731dc2a896b452259b4c63e37ce4c" prot="public" static="no" mutable="no">
        <type>int</type>
        <definition>int Test.someField</definition>
        <argsstring></argsstring>
        <name>someField</name>
        ...
        <location file="Test.java" line="3" column="16" bodyfile="Test.java" bodystart="3" bodyend="-1"/>
      </memberdef>
      </sectiondef>
      <sectiondef kind="public-func">
      <memberdef kind="function" id="classTest_1ae5eaada7e3b388b5e319240398670c34" prot="public" static="no" const="no" explicit="no" inline="yes" virt="non-virtual">
        <type>void some</type>
        <definition>void some Test.$method</definition>
        <argsstring>()</argsstring>
        <name>$method</name>
        ...
        <location file="Test.java" line="4" column="21" bodyfile="Test.java" bodystart="4" bodyend="4"/>
      </memberdef>
```
Please note that the ``$`` sign is a legal character for Java identifiers.
https://docs.oracle.com/javase/specs/jls/se16/html/jls-3.html#jls-3.8

The issue also applies to ``$`` occurring in class/interface/etc names.
Even worse: If one has two classes ``Test`` and ``Test$`` Doxygen will combine them into one xml file. It contains both of their members as if they were in one class. I did not even test what happens in case of member name collisions then.

**Expected behavior**
I expect that for Java identifiers, the ``$`` sign is treated like any other legal character.
The resulting code snippet should be
```
<memberdef kind="variable" id="classTest_1a815731dc2a896b452259b4c63e37ce4c" prot="public" static="no" mutable="no">
        <type>int</type>
        <definition>int Test.someField$</definition>
        <argsstring></argsstring>
        <name>someField$</name>
        ...
        <location file="Test.java" line="3" column="16" bodyfile="Test.java" bodystart="3" bodyend="-1"/>
      </memberdef>
      </sectiondef>
      <sectiondef kind="public-func">
      <memberdef kind="function" id="classTest_1ae5eaada7e3b388b5e319240398670c34" prot="public" static="no" const="no" explicit="no" inline="yes" virt="non-virtual">
        <type>void</type>
        <definition>void Test.some$method</definition>
        <argsstring>()</argsstring>
        <name>some$method</name>
        ...
        <location file="Test.java" line="4" column="21" bodyfile="Test.java" bodystart="4" bodyend="4"/>
      </memberdef>
```

**To Reproduce**
Find a Java file and doxygen config attached. The issue is demonstrated like mentioned above.
After running doxygen on the example, the files in the subfolder ``xml`` contain the snippet shown above.
[issue_dollar.zip](https://github.com/doxygen/doxygen/files/6703519/issue_dollar.zip)

**Version**
Tested with doxygen clone from 2021-05-26:
```
/blah/doxygen/build/bin/doxygen -v
1.9.2 (da0a6b42c349bc06b2804a4b0e8f55c7690f5cf9*)
```

`lsb_release -a`:
```
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	LinuxMint
Description:	Linux Mint 18 Sarah
Release:	18
Codename:	sarah
```

**Additional context**
I know the dollar sign is rarely used and not recommended in Java identifiers. However, in large code bases it occurs from time to time. This issue makes the doc unreliable and messy wherever a ``$`` occurs.

**Comment by albert-github** [comment]
Not withstanding the remark that `$` should not be use except for generated code:
> The "Java letters" include uppercase and lowercase ASCII Latin letters A-Z (\u0041-\u005a), and a-z (\u0061-\u007a), and, for historical reasons, the ASCII dollar sign ($, or \u0024) and underscore (_, or \u005f). The dollar sign should be used only in mechanically generated source code or, rarely, to access pre-existing names on legacy systems. The underscore may be used in identifiers formed of two or more characters, but it cannot be used as a one-character identifier due to being a keyword. 


I've just pushed a proposed patch, pull request #8621

**Comment by Stewori** [comment]
Totally agree that it shouldn't be used if one has a choice. This issue is about running Doxygen on code one does not have control over, or one wouldn't want to change, e.g. because the risk of breaking something is too high (or the management deems documentation a poor reason for refactoring). I believe there are plenty of reasons to leave some given code it its original form (e.g. because it is from a certain release and frozen). And if in the history someone happened to be so short sighted to use ``$`` in some identifier, doc would be broken.

So, thanks for fixing! I will check out your commit.

**Comment by Stewori** [comment]
(For the record, I believe this would have deserved the bug-label. E.g. potentially clashing members of two distinct classes Test and Test$ into the same compound is IMHO incorrect behavior. Unlikely, yes; but still incorrect on actually valid Java code.)

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
