### ISSUE TITLE
Build error with git head GCC (version 12, Nov 2021)

### ISSUE THREAD

**Issue by paulfloyd** [doxygen/doxygen#8909]
```
[ 32%] Building CXX object src/CMakeFiles/doxymain.dir/markdown.cpp.o
In file included from .../doxygen/src/markdown.h:23,
                 from .../doxygen/src/markdown.cpp:40:
.../doxygen/src/growbuf.h: In constructor 'GrowBuf::GrowBuf(GrowBuf&&)':
.../doxygen/src/growbuf.h:37:20: error: 'exchange' is not a member of 'std'
   37 |       : m_str(std::exchange(other.m_str,(char*)0))
      |                    ^~~~~~~~
.../doxygen/src/growbuf.h:38:20: error: 'exchange' is not a member of 'std'
   38 |       , m_pos(std::exchange(other.m_pos,0))
      |                    ^~~~~~~~
.../doxygen/src/growbuf.h:39:20: error: 'exchange' is not a member of 'std'
   39 |       , m_len(std::exchange(other.m_len,0))
      |                    ^~~~~~~~
.../doxygen/src/growbuf.h: In member function 'GrowBuf& GrowBuf::operator=(GrowBuf&&)':
.../doxygen/src/growbuf.h:46:20: error: 'exchange' is not a member of 'std'
   46 |       m_len = std::exchange(other.m_len,0);
      |                    ^~~~~~~~
.../doxygen/src/growbuf.h:47:20: error: 'exchange' is not a member of 'std'
   47 |       m_pos = std::exchange(other.m_pos,0);
      |                    ^~~~~~~~
.../doxygen/src/growbuf.h:48:20: error: 'exchange' is not a member of 'std'
   48 |       m_str = std::exchange(other.m_str,(char*)0);
      |                    ^~~~~~~~
make[2]: *** [src/CMakeFiles/doxymain.dir/build.make:1512: src/CMakeFiles/doxymain.dir/markdown.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:512: src/CMakeFiles/doxymain.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

If I add `#include <utility>` to growbuf.h then it builds OK

This is with doxygen from git head @ github, 
commit e321a870fda2c1c5bf759d6320b0063675f79fcd (HEAD -> master, origin/master, origin/HEAD)

**Comment by albert-github** [comment]
- Which version of doxygen are you compiling?
- can you give a few more lines before (and after) the current snippet?

**Comment by albert-github** [comment]
Even though GCC version 12 has not yet been released I've just pushed a proposed patch, pull request #8910.

Please still answer the questions posted in the previous comment (https://github.com/doxygen/doxygen/issues/8909#issuecomment-977823507).

**Comment by paulfloyd** [comment]
I'll update my original post in a moment.

The change I made to fix the build was almost the same (I added `utility` to the end of the list of includes, which I don't believe will make any difference).

It seems fairly clear to me that the problem was that previously this worked by chance since one standard header or another indirectly included `utility`. Now the libstdc++ with GCC 12 no longer has that indirect include and the header no longer compiles.

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by brechtsanders** [comment]
GCC 12.1.0 as just released, and I still get this issue building Doxygen 1.9.4
```
FAILED: src/CMakeFiles/doxycfg.dir/message.cpp.obj
D:\Prog\winlibs64_stage\mingw64\bin\c++.exe -DYY_BUF_SIZE=262144 -DYY_READ_BUF_SIZE=262144 -ID:/Prog/winlibs64_stage/custombuilt -IR:/winlibs64_stage/doxygen-1.9.4/filesystem -IR:/winlibs64_stage/doxygen-1.9.4/libmd5 -IR:/winlibs64_stage/doxygen-1.9.4/liblodepng -IR:/winlibs64_stage/doxygen-1.9.4/libmscgen -IR:/winlibs64_stage/doxygen-1.9.4/libversion -IR:/winlibs64_stage/doxygen-1.9.4/libxml -IR:/winlibs64_stage/doxygen-1.9.4/vhdlparser -IR:/winlibs64_stage/doxygen-1.9.4/src -IR:/winlibs64_stage/doxygen-1.9.4/build_win/generated_src -O3 -DNDEBUG -fvisibility=hidden -fno-keep-inline-dllexport -Wall -Wextra -Wshadow -Wnon-virtual-dtor -Wcast-align -Wunused -Woverloaded-virtual -Wpedantic -Wdouble-promotion -Wformat=2 -Wno-unused-parameter -Wno-sign-conversion -Wno-format-nonliteral -Wno-implicit-fallthrough -std=gnu++17 -MD -MT src/CMakeFiles/doxycfg.dir/message.cpp.obj -MF src\CMakeFiles\doxycfg.dir\message.cpp.obj.d -o src/CMakeFiles/doxycfg.dir/message.cpp.obj -c R:/winlibs64_stage/doxygen-1.9.4/src/message.cpp
In file included from R:/winlibs64_stage/doxygen-1.9.4/src/doxygen.h:24,
                 from R:/winlibs64_stage/doxygen-1.9.4/src/message.cpp:21:
R:/winlibs64_stage/doxygen-1.9.4/src/cache.h: In member function 'V* Cache<K, V>::insert(const K&, V&&)':
R:/winlibs64_stage/doxygen-1.9.4/src/cache.h:53:14: error: 'exchange' is not a member of 'std'
   53 |         std::exchange(it->second->second,value);
      |              ^~~~~~~~
```

**Comment by albert-github** [comment]
You are right, there has already been an issue for this #9312 (and it is solved in master).

The problem is that the necessity to use `<utility>` is a breaking change in GCC version 12. The C++ standard only gives minimum requirements regarding the contents of the (standard) include files, but an include file can include other (standard) include files as well, this is all at the liberty of the compiler builder.

At the moment of the update for this issue (#8909 / #8910) the `std::echange` was only in `growbuf` and fixed there. The use of `std::exchange` in `cache.h` was added on April 28, 2022 (commit: fe58686503d386afb5269e7a2799c0457c743092  "Fixed potential crash in case cached item was already purged") and due to the different compilers used (and not using the GCC 12 compiler) this was not detected.
