### ISSUE TITLE
Support collapsible sections in markdown

### ISSUE THREAD

**Issue by asklar** [doxygen/doxygen#9016]
**Describe the bug**
When adding a markdown file that contains a collapsible section like:
```
<details>
  <summary>Examples</summary>
  Bunch of details
</details>
```

This is not rendered correctly by doxygen, even though it's a fairly standard markdown feature (present in github markdown, for example).

**Expected behavior**
Collapsible sections should be correctly rendered

**Screenshots**
Actual rendering:

![image](https://user-images.githubusercontent.com/22989529/148600135-ede3b120-e25e-43ee-85cc-a7acb062c7ef.png)

Expected:

collapsed: 
![image](https://user-images.githubusercontent.com/22989529/148599987-81a9b857-0c86-476f-8a14-049d5a9dbaab.png)

uncollapsed:
![image](https://user-images.githubusercontent.com/22989529/148600016-a2be8923-1885-41f8-9a78-95f9083e9e4b.png)

**To Reproduce**
set up doxygen to include an index.md as input, and add the snippet mentioned above.

**Version**
1.9.2 - Windows 11 64bit.

**Comment by albert-github** [comment]
With the doxygen version 1.9.2 this feature is not implemented
With the current version of doxygen (1.9.3) I see with:
```
# Some page

Here we have a collapsable section:
<details>
  <summary>Examples</summary>
  Bunch of details
</details>
```
Result:
![image](https://user-images.githubusercontent.com/5223533/148640500-a6fff6a3-f579-40ce-bba4-49b640ff83fc.png)

and
![image](https://user-images.githubusercontent.com/5223533/148640493-d33cbf75-6631-4b29-b434-ad909d7cf87a.png)


The relevant pull request:  HTML tag details #8890 

So I think the problem has been solved in the mean time.

**Comment by asklar** [comment]
Hi @albert-github / @doxygen , I just tried this on 1.9.3 and it's still broken:

```
<details>
  <summary>Title of details</summary>

    **Here is a code block 1**
    ```
    void f() { }
    ```

    **Here is a code block #2**
    ```
      void g() { }
    ```
</details>
```

Result:
<img width="243" alt="image" src="https://user-images.githubusercontent.com/22989529/167019083-1a08003e-59a5-465f-b3f3-812c6d12454c.png">


Note how every code block shows up in a different expander

**Comment by albert-github** [comment]
Doesn't look nice, reopening issue.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9331 containing a new implementation for the HTML details tag.

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by asklar** [comment]
thanks a lot @albert-github, looking forward to trying this out :)

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.5.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
